// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_5WPnHMCKqzaaAWGcU9vdmsKDvobQK4',
    appId: '1:146283361860:android:1fbae5f0dc8e4b4a41ae11',
    messagingSenderId: '146283361860',
    projectId: 'todo-eisenhower-app',
    storageBucket: 'todo-eisenhower-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPHpiLJ6k8n7zk3VnIVcEydL5c7pt-n9A',
    appId: '1:146283361860:ios:b80641c94dbd2bfd41ae11',
    messagingSenderId: '146283361860',
    projectId: 'todo-eisenhower-app',
    storageBucket: 'todo-eisenhower-app.firebasestorage.app',
    iosBundleId: 'com.eisenhower.todo.todoEisenhower',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPHpiLJ6k8n7zk3VnIVcEydL5c7pt-n9A',
    appId: '1:146283361860:ios:b80641c94dbd2bfd41ae11',
    messagingSenderId: '146283361860',
    projectId: 'todo-eisenhower-app',
    storageBucket: 'todo-eisenhower-app.firebasestorage.app',
    iosBundleId: 'com.eisenhower.todo.todoEisenhower',
  );
}
